warehouseA:
    initial_stock: 30
    threshold: 10

warehouseB:
    initial_stock: 40
    threshold: 15

delivery_amount: 25

number_of_production_lines: 4
required_A_amount: 2
required_B_amount: 3

package_capacity: 5